### ISSUE TITLE
Enable video conferencing controls in PiP window

### ISSUE THREAD

**Issue by dawnpro7** [arnellebalane/google-meet-pip#12]
Hey, I would like to have something like this. Whenever I share my entire screen it is hard to mute and unmute. Is there any way to add the mute and unmute button to the pip extension. If it is possible it will be very helpful. Thank you.

**Comment by arnellebalane** [comment]
Hey @dawntom2006 thanks for this feature request, yes I believe this is possible 😄

**Comment by dawntom2006** [comment]
Awesome. Eagerly waiting for that.

**Comment by dawntom2006** [comment]
Hey any updates on this function. Sorry for forcing you.

**Comment by arnellebalane** [comment]
Hey @dawntom2006 thank you for your patience. I mostly finished implementing this feature already, however I'm unable to release it at this time because an update in Chrome broke how the extension works, so it will be unusable anyway. More details in #17 

I'll try to find time to fix that other issue this weekend to I can release this feature.

**Comment by dawntom2006** [comment]
oh tysm for trying to add it. oh that's too sad

**Comment by arnellebalane** [comment]
Hi @dawnpro7 , this is already published in `v1.2.0` of the extension. I hope you find it useful. Thank you! 🙇 
![image](https://user-images.githubusercontent.com/1428598/151570314-1e3c3e40-8efd-4763-9b64-d194f2b780d3.png)
