### ISSUE TITLE
History permission

### ISSUE THREAD

**Issue by thelewiss1** [arnellebalane/google-meet-pip#9]
Hi there! Why does the extension need access to the browsing history?

Thanks!

**Comment by arnellebalane** [comment]
Hey @thelewiss1 , thanks for pointing this out.

The extension doesn't actually do anything related to the browsing history (read, write, etc.). It seems that the "Can read your browsing history" in the prompt when installing the extension comes from the usage fo the [`tabs` permission](https://github.com/arnellebalane/google-meet-pip/blob/main/manifest.json#L36). 

Unfortunately there's nothing that I can do about that prompt for now, as the extension needs that that permission in order to work properly.
